version: '3.8'

services:
  app:
    build: .
    ports:
      - "8051:80"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: chatcare_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatcare_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
